apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: silly-demo-db
spec:
  clusterDefinitionRef: postgresql
  clusterVersionRef: postgresql-14.8.0
  terminationPolicy: Delete
  componentSpecs:
    - name: postgresql
      componentDefRef: postgresql
      switchPolicy:
        type: Noop
      monitor: true
      replicas: 3
      resources:
        limits:
          cpu: "0.5"
          memory: "0.5Gi"
        requests:
          cpu: "0.5"
          memory: "0.5Gi"
